apiVersion: v1
kind: ConfigMap
metadata:
  name: costcenter-config
data:
  app.properties: |2+
    quarkus.qpid-jms.url=amqp://messaging-5a557d5.workshop-operators.svc:5672
    quarkus.qpid-jms.username=user
    quarkus.qpid-jms.password=enmasse
    camel.component.kafka.brokers=moon-kafka-bootstrap.user6.svc:9092